export const nigerianStates = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa',
  'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo',
  'Ekiti', 'Enugu', 'FCT - Abuja', 'Gombe', 'Imo', 'Jigawa',
  'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
  'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun',
  'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara'
]

export const nigerianCities = {
  'Abia': ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu', 'Bende'],
  'Adamawa': ['Yola', 'Mubi', 'Numan', 'Ganye', 'Jimeta'],
  'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak'],
  'Anambra': ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Ihiala'],
  'Bauchi': ['Bauchi', 'Azare', 'Misau', 'Katagum', 'Jama\'are'],
  'Bayelsa': ['Yenagoa', 'Brass', 'Nembe', 'Ogbia', 'Sagbama'],
  'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya'],
  'Borno': ['Maiduguri', 'Biu', 'Dikwa', 'Gwoza', 'Ngala'],
  'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Obudu', 'Ugep'],
  'Delta': ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Agbor'],
  'Ebonyi': ['Abakaliki', 'Afikpo', 'Onueke', 'Ezza', 'Ishieke'],
  'Edo': ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Igarra'],
  'Ekiti': ['Ado Ekiti', 'Ikere Ekiti', 'Ilawe Ekiti', 'Ijero Ekiti', 'Emure Ekiti'],
  'Enugu': ['Enugu', 'Nsukka', 'Agbani', 'Awgu', 'Oji River'],
  'FCT - Abuja': ['Abuja', 'Gwagwalada', 'Kuje', 'Bwari', 'Kubwa'],
  'Gombe': ['Gombe', 'Kaltungo', 'Billiri', 'Nafada', 'Dukku'],
  'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Oguta', 'Mbaise'],
  'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Birnin Kudu', 'Kazaure'],
  'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Kagoro', 'Saminaka'],
  'Kano': ['Kano', 'Wudil', 'Rano', 'Gwarzo', 'Dambatta'],
  'Katsina': ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Mani'],
  'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Koko'],
  'Kogi': ['Lokoja', 'Okene', 'Kabba', 'Idah', 'Ankpa'],
  'Kwara': ['Ilorin', 'Offa', 'Omu-Aran', 'Lafiagi', 'Patigi'],
  'Lagos': ['Ikeja', 'Lagos Island', 'Lekki', 'Surulere', 'Yaba', 'Ajah', 'Badagry', 'Epe', 'Ikorodu', 'Mushin'],
  'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa', 'Doma'],
  'Niger': ['Minna', 'Bida', 'Suleja', 'Kontagora', 'Lapai'],
  'Ogun': ['Abeokuta', 'Ijebu Ode', 'Sagamu', 'Ilaro', 'Ota'],
  'Ondo': ['Akure', 'Ondo', 'Owo', 'Ikare', 'Okitipupa'],
  'Osun': ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo'],
  'Oyo': ['Ibadan', 'Ogbomosho', 'Oyo', 'Iseyin', 'Saki'],
  'Plateau': ['Jos', 'Bukuru', 'Shendam', 'Pankshin', 'Langtang'],
  'Rivers': ['Port Harcourt', 'Bonny', 'Degema', 'Ahoada', 'Omoku'],
  'Sokoto': ['Sokoto', 'Tambuwal', 'Wurno', 'Gwadabawa', 'Illela'],
  'Taraba': ['Jalingo', 'Wukari', 'Bali', 'Gembu', 'Takum'],
  'Yobe': ['Damaturu', 'Potiskum', 'Nguru', 'Gashua', 'Geidam'],
  'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Maru']
}
